/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as academy_analytics from "../academy/analytics.js";
import type * as academy_content from "../academy/content.js";
import type * as academy_lib_auth from "../academy/lib/auth.js";
import type * as academy_participants from "../academy/participants.js";
import type * as academy_questions from "../academy/questions.js";
import type * as academy_results from "../academy/results.js";
import type * as academy_settings from "../academy/settings.js";
import type * as academyParticipants from "../academyParticipants.js";
import type * as academyQuestions from "../academyQuestions.js";
import type * as academyResults from "../academyResults.js";
import type * as academySettings from "../academySettings.js";
import type * as accessRequests from "../accessRequests.js";
import type * as accountLinks from "../accountLinks.js";
import type * as activity_access from "../activity/access.js";
import type * as activity_agentVersion from "../activity/agentVersion.js";
import type * as activity_audit from "../activity/audit.js";
import type * as activity_clockodo from "../activity/clockodo.js";
import type * as activity_deviceAuth from "../activity/deviceAuth.js";
import type * as activity_devices from "../activity/devices.js";
import type * as activity_events from "../activity/events.js";
import type * as activity_genesys from "../activity/genesys.js";
import type * as activity_ingest from "../activity/ingest.js";
import type * as activity_integrations from "../activity/integrations.js";
import type * as activity_lib_audit from "../activity/lib/audit.js";
import type * as activity_lib_businessHours from "../activity/lib/businessHours.js";
import type * as activity_lib_clockodo from "../activity/lib/clockodo.js";
import type * as activity_lib_clockodoDay from "../activity/lib/clockodoDay.js";
import type * as activity_lib_contracts from "../activity/lib/contracts.js";
import type * as activity_lib_crypto from "../activity/lib/crypto.js";
import type * as activity_lib_deviceAuth from "../activity/lib/deviceAuth.js";
import type * as activity_lib_events from "../activity/lib/events.js";
import type * as activity_lib_genesys from "../activity/lib/genesys.js";
import type * as activity_lib_integrationsShared from "../activity/lib/integrationsShared.js";
import type * as activity_lib_migration from "../activity/lib/migration.js";
import type * as activity_lib_patterns from "../activity/lib/patterns.js";
import type * as activity_lib_people from "../activity/lib/people.js";
import type * as activity_lib_settings from "../activity/lib/settings.js";
import type * as activity_lib_signals from "../activity/lib/signals.js";
import type * as activity_lib_state from "../activity/lib/state.js";
import type * as activity_maintenance from "../activity/maintenance.js";
import type * as activity_migration from "../activity/migration.js";
import type * as activity_migrationExport from "../activity/migrationExport.js";
import type * as activity_migrationRun from "../activity/migrationRun.js";
import type * as activity_patternReports from "../activity/patternReports.js";
import type * as activity_people from "../activity/people.js";
import type * as activity_reports from "../activity/reports.js";
import type * as activity_settings from "../activity/settings.js";
import type * as activity_state from "../activity/state.js";
import type * as activity_stats from "../activity/stats.js";
import type * as adminOverview from "../adminOverview.js";
import type * as aiRuns from "../aiRuns.js";
import type * as analytics from "../analytics.js";
import type * as announcements from "../announcements.js";
import type * as applicantVault from "../applicantVault.js";
import type * as applicants from "../applicants.js";
import type * as approvalDelegations from "../approvalDelegations.js";
import type * as auditLog from "../auditLog.js";
import type * as blog_analytics from "../blog/analytics.js";
import type * as blog_lib_sharing from "../blog/lib/sharing.js";
import type * as blog_posts from "../blog/posts.js";
import type * as blog_sharing from "../blog/sharing.js";
import type * as blogAnalytics from "../blogAnalytics.js";
import type * as blogPosts from "../blogPosts.js";
import type * as chat from "../chat.js";
import type * as clerkSync from "../clerkSync.js";
import type * as clockodoWebhookLog from "../clockodoWebhookLog.js";
import type * as companies from "../companies.js";
import type * as companyRoles from "../companyRoles.js";
import type * as crons from "../crons.js";
import type * as customRoles from "../customRoles.js";
import type * as designFeedback from "../designFeedback.js";
import type * as draftShares from "../draftShares.js";
import type * as drafts from "../drafts.js";
import type * as drafts_drafts from "../drafts/drafts.js";
import type * as drafts_lib_drafts from "../drafts/lib/drafts.js";
import type * as drafts_lib_surfaces from "../drafts/lib/surfaces.js";
import type * as drafts_shares from "../drafts/shares.js";
import type * as emails from "../emails.js";
import type * as errorCategories from "../errorCategories.js";
import type * as errorMeasures from "../errorMeasures.js";
import type * as errorReports from "../errorReports.js";
import type * as errorSettings from "../errorSettings.js";
import type * as events from "../events.js";
import type * as featureFlags from "../featureFlags.js";
import type * as fehlermanagement_categories from "../fehlermanagement/categories.js";
import type * as fehlermanagement_lib_thresholds from "../fehlermanagement/lib/thresholds.js";
import type * as fehlermanagement_measures from "../fehlermanagement/measures.js";
import type * as fehlermanagement_reports from "../fehlermanagement/reports.js";
import type * as fehlermanagement_settings from "../fehlermanagement/settings.js";
import type * as files from "../files.js";
import type * as functions from "../functions.js";
import type * as guidebookAttachments from "../guidebookAttachments.js";
import type * as guidebookFeedback from "../guidebookFeedback.js";
import type * as guidebookHighlights from "../guidebookHighlights.js";
import type * as guidebookPages from "../guidebookPages.js";
import type * as guidebookReads from "../guidebookReads.js";
import type * as guidebooks_attachments from "../guidebooks/attachments.js";
import type * as guidebooks_feedback from "../guidebooks/feedback.js";
import type * as guidebooks_highlights from "../guidebooks/highlights.js";
import type * as guidebooks_pages from "../guidebooks/pages.js";
import type * as guidebooks_reads from "../guidebooks/reads.js";
import type * as hr_applicants from "../hr/applicants.js";
import type * as hr_employees from "../hr/employees.js";
import type * as hr_lib_access from "../hr/lib/access.js";
import type * as hr_lib_retention from "../hr/lib/retention.js";
import type * as hr_lib_vault from "../hr/lib/vault.js";
import type * as hr_retention from "../hr/retention.js";
import type * as hr_vault from "../hr/vault.js";
import type * as http from "../http.js";
import type * as humanResources from "../humanResources.js";
import type * as integrations_audit from "../integrations/audit.js";
import type * as integrations_clockodo_client from "../integrations/clockodo/client.js";
import type * as integrations_clockodo_users from "../integrations/clockodo/users.js";
import type * as integrations_clockodoAbsences from "../integrations/clockodoAbsences.js";
import type * as integrations_clockodoLink from "../integrations/clockodoLink.js";
import type * as integrations_clockodoView from "../integrations/clockodoView.js";
import type * as integrations_clockodoWebhookLog from "../integrations/clockodoWebhookLog.js";
import type * as integrations_debug from "../integrations/debug.js";
import type * as integrations_health from "../integrations/health.js";
import type * as integrations_lib_audit from "../integrations/lib/audit.js";
import type * as integrations_onedrive from "../integrations/onedrive.js";
import type * as integrations_posthog from "../integrations/posthog.js";
import type * as intranetPages from "../intranetPages.js";
import type * as invites from "../invites.js";
import type * as itTicketThreads from "../itTicketThreads.js";
import type * as itTickets from "../itTickets.js";
import type * as itTickets_lib_threads from "../itTickets/lib/threads.js";
import type * as itTickets_threads from "../itTickets/threads.js";
import type * as itTickets_tickets from "../itTickets/tickets.js";
import type * as lib_aiContext from "../lib/aiContext.js";
import type * as lib_aiRuns from "../lib/aiRuns.js";
import type * as lib_analytics from "../lib/analytics.js";
import type * as lib_attachments from "../lib/attachments.js";
import type * as lib_audience from "../lib/audience.js";
import type * as lib_auditLogWrite from "../lib/auditLogWrite.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_caller from "../lib/caller.js";
import type * as lib_chat from "../lib/chat.js";
import type * as lib_clerk from "../lib/clerk.js";
import type * as lib_clockodoId from "../lib/clockodoId.js";
import type * as lib_errors from "../lib/errors.js";
import type * as lib_featureFlags from "../lib/featureFlags.js";
import type * as lib_internalApi from "../lib/internalApi.js";
import type * as lib_navigateSearch from "../lib/navigateSearch.js";
import type * as lib_notify from "../lib/notify.js";
import type * as lib_pages from "../lib/pages.js";
import type * as lib_permissions from "../lib/permissions.js";
import type * as lib_profile from "../lib/profile.js";
import type * as lib_reporting from "../lib/reporting.js";
import type * as lib_stepUp from "../lib/stepUp.js";
import type * as lib_text from "../lib/text.js";
import type * as lib_trash from "../lib/trash.js";
import type * as lib_users from "../lib/users.js";
import type * as lib_validators from "../lib/validators.js";
import type * as marketing_account from "../marketing/account.js";
import type * as marketing_analytics from "../marketing/analytics.js";
import type * as marketing_emails from "../marketing/emails.js";
import type * as marketing_forms from "../marketing/forms.js";
import type * as marketing_inbox from "../marketing/inbox.js";
import type * as marketing_inquiries from "../marketing/inquiries.js";
import type * as marketing_leads from "../marketing/leads.js";
import type * as marketing_lib_inquiry from "../marketing/lib/inquiry.js";
import type * as marketing_mail from "../marketing/mail.js";
import type * as marketing_retention from "../marketing/retention.js";
import type * as marketingAnalytics from "../marketingAnalytics.js";
import type * as members from "../members.js";
import type * as migrations_backfillCustomRoleIds from "../migrations/backfillCustomRoleIds.js";
import type * as migrations_backfillInquiries from "../migrations/backfillInquiries.js";
import type * as migrations_backfillManageClockodoTeam from "../migrations/backfillManageClockodoTeam.js";
import type * as migrations_backfillPerformanceCompanyId from "../migrations/backfillPerformanceCompanyId.js";
import type * as migrations_dropGuestFields from "../migrations/dropGuestFields.js";
import type * as notifications from "../notifications.js";
import type * as notifications_email from "../notifications/email.js";
import type * as notifications_notifications from "../notifications/notifications.js";
import type * as offboarding from "../offboarding.js";
import type * as onedrive from "../onedrive.js";
import type * as org_auditLog from "../org/auditLog.js";
import type * as org_backups from "../org/backups.js";
import type * as org_contacts from "../org/contacts.js";
import type * as org_daysOff from "../org/daysOff.js";
import type * as org_delegations from "../org/delegations.js";
import type * as org_featureFlags from "../org/featureFlags.js";
import type * as org_lib_delegations from "../org/lib/delegations.js";
import type * as org_offboarding from "../org/offboarding.js";
import type * as org_overview from "../org/overview.js";
import type * as org_roles from "../org/roles.js";
import type * as org_search from "../org/search.js";
import type * as org_structure from "../org/structure.js";
import type * as org_structureMigration from "../org/structureMigration.js";
import type * as org_tools from "../org/tools.js";
import type * as org_trash from "../org/trash.js";
import type * as orgData from "../orgData.js";
import type * as orgDataMigration from "../orgDataMigration.js";
import type * as outbound from "../outbound.js";
import type * as passkeys from "../passkeys.js";
import type * as passwordResets from "../passwordResets.js";
import type * as people_accessRequests from "../people/accessRequests.js";
import type * as people_clerkSync from "../people/clerkSync.js";
import type * as people_invites from "../people/invites.js";
import type * as people_lib_provisioning from "../people/lib/provisioning.js";
import type * as people_members from "../people/members.js";
import type * as people_preferences from "../people/preferences.js";
import type * as people_presence from "../people/presence.js";
import type * as people_requests from "../people/requests.js";
import type * as people_sandbox from "../people/sandbox.js";
import type * as people_tourProgress from "../people/tourProgress.js";
import type * as people_users from "../people/users.js";
import type * as performance_auth from "../performance/auth.js";
import type * as performance_companies from "../performance/companies.js";
import type * as performance_export from "../performance/export.js";
import type * as performance_import from "../performance/import.js";
import type * as performance_lib_aggregatedTemplate from "../performance/lib/aggregatedTemplate.js";
import type * as performance_lib_auth from "../performance/lib/auth.js";
import type * as performance_lib_callImport from "../performance/lib/callImport.js";
import type * as performance_lib_interactionImport from "../performance/lib/interactionImport.js";
import type * as performance_lib_kpi from "../performance/lib/kpi.js";
import type * as performance_lib_permissions from "../performance/lib/permissions.js";
import type * as performance_lib_reports from "../performance/lib/reports.js";
import type * as performance_lib_salesforceImport from "../performance/lib/salesforceImport.js";
import type * as performance_lib_types from "../performance/lib/types.js";
import type * as performance_lib_workdays from "../performance/lib/workdays.js";
import type * as performance_lib_xlsxZip from "../performance/lib/xlsxZip.js";
import type * as performance_queries from "../performance/queries.js";
import type * as performance_roles from "../performance/roles.js";
import type * as performance_topics from "../performance/topics.js";
import type * as performance_uploadParse from "../performance/uploadParse.js";
import type * as performanceAuth from "../performanceAuth.js";
import type * as performanceExport from "../performanceExport.js";
import type * as performanceImport from "../performanceImport.js";
import type * as performanceQueries from "../performanceQueries.js";
import type * as performanceTopics from "../performanceTopics.js";
import type * as performanceUploadParse from "../performanceUploadParse.js";
import type * as presence from "../presence.js";
import type * as salesCoachEv_calls from "../salesCoachEv/calls.js";
import type * as salesCoachEv_settings from "../salesCoachEv/settings.js";
import type * as salesCoachEv_wiki from "../salesCoachEv/wiki.js";
import type * as salesCockpit from "../salesCockpit.js";
import type * as salesCockpit_flows from "../salesCockpit/flows.js";
import type * as salesCockpit_lexikon from "../salesCockpit/lexikon.js";
import type * as salesCockpit_projects from "../salesCockpit/projects.js";
import type * as salesCockpitFlows from "../salesCockpitFlows.js";
import type * as sandbox from "../sandbox.js";
import type * as secondaryEmails from "../secondaryEmails.js";
import type * as security_accountLinks from "../security/accountLinks.js";
import type * as security_lib_passwordResets from "../security/lib/passwordResets.js";
import type * as security_passkeys from "../security/passkeys.js";
import type * as security_passwordResets from "../security/passwordResets.js";
import type * as security_secondaryEmails from "../security/secondaryEmails.js";
import type * as security_stepUp from "../security/stepUp.js";
import type * as security_totp from "../security/totp.js";
import type * as sharing from "../sharing.js";
import type * as stepUp from "../stepUp.js";
import type * as suggestionCategories from "../suggestionCategories.js";
import type * as suggestions from "../suggestions.js";
import type * as suggestions_categories from "../suggestions/categories.js";
import type * as suggestions_suggestions from "../suggestions/suggestions.js";
import type * as tables_activity from "../tables/activity.js";
import type * as tables_ai from "../tables/ai.js";
import type * as tables_chat from "../tables/chat.js";
import type * as tables_comms from "../tables/comms.js";
import type * as tables_content from "../tables/content.js";
import type * as tables_hr from "../tables/hr.js";
import type * as tables_identity from "../tables/identity.js";
import type * as tables_integrations from "../tables/integrations.js";
import type * as tables_itTickets from "../tables/itTickets.js";
import type * as tables_marketing from "../tables/marketing.js";
import type * as tables_performance from "../tables/performance.js";
import type * as tables_sales from "../tables/sales.js";
import type * as tables_security from "../tables/security.js";
import type * as totp from "../totp.js";
import type * as tourProgress from "../tourProgress.js";
import type * as updates from "../updates.js";
import type * as updates_email from "../updates/email.js";
import type * as updates_internal from "../updates/internal.js";
import type * as updates_lib_updates from "../updates/lib/updates.js";
import type * as updates_updates from "../updates/updates.js";
import type * as updatesEmail from "../updatesEmail.js";
import type * as updatesInternal from "../updatesInternal.js";
import type * as userPreferences from "../userPreferences.js";
import type * as users from "../users.js";
import type * as whitepaperLeads from "../whitepaperLeads.js";
import type * as wiki_categories from "../wiki/categories.js";
import type * as wiki_chats from "../wiki/chats.js";
import type * as wiki_entries from "../wiki/entries.js";
import type * as wiki_formatSettings from "../wiki/formatSettings.js";
import type * as wiki_migration from "../wiki/migration.js";
import type * as wikiCategories from "../wikiCategories.js";
import type * as wikiChats from "../wikiChats.js";
import type * as wikiEntries from "../wikiEntries.js";
import type * as wikiFormatSettings from "../wikiFormatSettings.js";
import type * as wikiMigration from "../wikiMigration.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "academy/analytics": typeof academy_analytics;
  "academy/content": typeof academy_content;
  "academy/lib/auth": typeof academy_lib_auth;
  "academy/participants": typeof academy_participants;
  "academy/questions": typeof academy_questions;
  "academy/results": typeof academy_results;
  "academy/settings": typeof academy_settings;
  academyParticipants: typeof academyParticipants;
  academyQuestions: typeof academyQuestions;
  academyResults: typeof academyResults;
  academySettings: typeof academySettings;
  accessRequests: typeof accessRequests;
  accountLinks: typeof accountLinks;
  "activity/access": typeof activity_access;
  "activity/agentVersion": typeof activity_agentVersion;
  "activity/audit": typeof activity_audit;
  "activity/clockodo": typeof activity_clockodo;
  "activity/deviceAuth": typeof activity_deviceAuth;
  "activity/devices": typeof activity_devices;
  "activity/events": typeof activity_events;
  "activity/genesys": typeof activity_genesys;
  "activity/ingest": typeof activity_ingest;
  "activity/integrations": typeof activity_integrations;
  "activity/lib/audit": typeof activity_lib_audit;
  "activity/lib/businessHours": typeof activity_lib_businessHours;
  "activity/lib/clockodo": typeof activity_lib_clockodo;
  "activity/lib/clockodoDay": typeof activity_lib_clockodoDay;
  "activity/lib/contracts": typeof activity_lib_contracts;
  "activity/lib/crypto": typeof activity_lib_crypto;
  "activity/lib/deviceAuth": typeof activity_lib_deviceAuth;
  "activity/lib/events": typeof activity_lib_events;
  "activity/lib/genesys": typeof activity_lib_genesys;
  "activity/lib/integrationsShared": typeof activity_lib_integrationsShared;
  "activity/lib/migration": typeof activity_lib_migration;
  "activity/lib/patterns": typeof activity_lib_patterns;
  "activity/lib/people": typeof activity_lib_people;
  "activity/lib/settings": typeof activity_lib_settings;
  "activity/lib/signals": typeof activity_lib_signals;
  "activity/lib/state": typeof activity_lib_state;
  "activity/maintenance": typeof activity_maintenance;
  "activity/migration": typeof activity_migration;
  "activity/migrationExport": typeof activity_migrationExport;
  "activity/migrationRun": typeof activity_migrationRun;
  "activity/patternReports": typeof activity_patternReports;
  "activity/people": typeof activity_people;
  "activity/reports": typeof activity_reports;
  "activity/settings": typeof activity_settings;
  "activity/state": typeof activity_state;
  "activity/stats": typeof activity_stats;
  adminOverview: typeof adminOverview;
  aiRuns: typeof aiRuns;
  analytics: typeof analytics;
  announcements: typeof announcements;
  applicantVault: typeof applicantVault;
  applicants: typeof applicants;
  approvalDelegations: typeof approvalDelegations;
  auditLog: typeof auditLog;
  "blog/analytics": typeof blog_analytics;
  "blog/lib/sharing": typeof blog_lib_sharing;
  "blog/posts": typeof blog_posts;
  "blog/sharing": typeof blog_sharing;
  blogAnalytics: typeof blogAnalytics;
  blogPosts: typeof blogPosts;
  chat: typeof chat;
  clerkSync: typeof clerkSync;
  clockodoWebhookLog: typeof clockodoWebhookLog;
  companies: typeof companies;
  companyRoles: typeof companyRoles;
  crons: typeof crons;
  customRoles: typeof customRoles;
  designFeedback: typeof designFeedback;
  draftShares: typeof draftShares;
  drafts: typeof drafts;
  "drafts/drafts": typeof drafts_drafts;
  "drafts/lib/drafts": typeof drafts_lib_drafts;
  "drafts/lib/surfaces": typeof drafts_lib_surfaces;
  "drafts/shares": typeof drafts_shares;
  emails: typeof emails;
  errorCategories: typeof errorCategories;
  errorMeasures: typeof errorMeasures;
  errorReports: typeof errorReports;
  errorSettings: typeof errorSettings;
  events: typeof events;
  featureFlags: typeof featureFlags;
  "fehlermanagement/categories": typeof fehlermanagement_categories;
  "fehlermanagement/lib/thresholds": typeof fehlermanagement_lib_thresholds;
  "fehlermanagement/measures": typeof fehlermanagement_measures;
  "fehlermanagement/reports": typeof fehlermanagement_reports;
  "fehlermanagement/settings": typeof fehlermanagement_settings;
  files: typeof files;
  functions: typeof functions;
  guidebookAttachments: typeof guidebookAttachments;
  guidebookFeedback: typeof guidebookFeedback;
  guidebookHighlights: typeof guidebookHighlights;
  guidebookPages: typeof guidebookPages;
  guidebookReads: typeof guidebookReads;
  "guidebooks/attachments": typeof guidebooks_attachments;
  "guidebooks/feedback": typeof guidebooks_feedback;
  "guidebooks/highlights": typeof guidebooks_highlights;
  "guidebooks/pages": typeof guidebooks_pages;
  "guidebooks/reads": typeof guidebooks_reads;
  "hr/applicants": typeof hr_applicants;
  "hr/employees": typeof hr_employees;
  "hr/lib/access": typeof hr_lib_access;
  "hr/lib/retention": typeof hr_lib_retention;
  "hr/lib/vault": typeof hr_lib_vault;
  "hr/retention": typeof hr_retention;
  "hr/vault": typeof hr_vault;
  http: typeof http;
  humanResources: typeof humanResources;
  "integrations/audit": typeof integrations_audit;
  "integrations/clockodo/client": typeof integrations_clockodo_client;
  "integrations/clockodo/users": typeof integrations_clockodo_users;
  "integrations/clockodoAbsences": typeof integrations_clockodoAbsences;
  "integrations/clockodoLink": typeof integrations_clockodoLink;
  "integrations/clockodoView": typeof integrations_clockodoView;
  "integrations/clockodoWebhookLog": typeof integrations_clockodoWebhookLog;
  "integrations/debug": typeof integrations_debug;
  "integrations/health": typeof integrations_health;
  "integrations/lib/audit": typeof integrations_lib_audit;
  "integrations/onedrive": typeof integrations_onedrive;
  "integrations/posthog": typeof integrations_posthog;
  intranetPages: typeof intranetPages;
  invites: typeof invites;
  itTicketThreads: typeof itTicketThreads;
  itTickets: typeof itTickets;
  "itTickets/lib/threads": typeof itTickets_lib_threads;
  "itTickets/threads": typeof itTickets_threads;
  "itTickets/tickets": typeof itTickets_tickets;
  "lib/aiContext": typeof lib_aiContext;
  "lib/aiRuns": typeof lib_aiRuns;
  "lib/analytics": typeof lib_analytics;
  "lib/attachments": typeof lib_attachments;
  "lib/audience": typeof lib_audience;
  "lib/auditLogWrite": typeof lib_auditLogWrite;
  "lib/auth": typeof lib_auth;
  "lib/caller": typeof lib_caller;
  "lib/chat": typeof lib_chat;
  "lib/clerk": typeof lib_clerk;
  "lib/clockodoId": typeof lib_clockodoId;
  "lib/errors": typeof lib_errors;
  "lib/featureFlags": typeof lib_featureFlags;
  "lib/internalApi": typeof lib_internalApi;
  "lib/navigateSearch": typeof lib_navigateSearch;
  "lib/notify": typeof lib_notify;
  "lib/pages": typeof lib_pages;
  "lib/permissions": typeof lib_permissions;
  "lib/profile": typeof lib_profile;
  "lib/reporting": typeof lib_reporting;
  "lib/stepUp": typeof lib_stepUp;
  "lib/text": typeof lib_text;
  "lib/trash": typeof lib_trash;
  "lib/users": typeof lib_users;
  "lib/validators": typeof lib_validators;
  "marketing/account": typeof marketing_account;
  "marketing/analytics": typeof marketing_analytics;
  "marketing/emails": typeof marketing_emails;
  "marketing/forms": typeof marketing_forms;
  "marketing/inbox": typeof marketing_inbox;
  "marketing/inquiries": typeof marketing_inquiries;
  "marketing/leads": typeof marketing_leads;
  "marketing/lib/inquiry": typeof marketing_lib_inquiry;
  "marketing/mail": typeof marketing_mail;
  "marketing/retention": typeof marketing_retention;
  marketingAnalytics: typeof marketingAnalytics;
  members: typeof members;
  "migrations/backfillCustomRoleIds": typeof migrations_backfillCustomRoleIds;
  "migrations/backfillInquiries": typeof migrations_backfillInquiries;
  "migrations/backfillManageClockodoTeam": typeof migrations_backfillManageClockodoTeam;
  "migrations/backfillPerformanceCompanyId": typeof migrations_backfillPerformanceCompanyId;
  "migrations/dropGuestFields": typeof migrations_dropGuestFields;
  notifications: typeof notifications;
  "notifications/email": typeof notifications_email;
  "notifications/notifications": typeof notifications_notifications;
  offboarding: typeof offboarding;
  onedrive: typeof onedrive;
  "org/auditLog": typeof org_auditLog;
  "org/backups": typeof org_backups;
  "org/contacts": typeof org_contacts;
  "org/daysOff": typeof org_daysOff;
  "org/delegations": typeof org_delegations;
  "org/featureFlags": typeof org_featureFlags;
  "org/lib/delegations": typeof org_lib_delegations;
  "org/offboarding": typeof org_offboarding;
  "org/overview": typeof org_overview;
  "org/roles": typeof org_roles;
  "org/search": typeof org_search;
  "org/structure": typeof org_structure;
  "org/structureMigration": typeof org_structureMigration;
  "org/tools": typeof org_tools;
  "org/trash": typeof org_trash;
  orgData: typeof orgData;
  orgDataMigration: typeof orgDataMigration;
  outbound: typeof outbound;
  passkeys: typeof passkeys;
  passwordResets: typeof passwordResets;
  "people/accessRequests": typeof people_accessRequests;
  "people/clerkSync": typeof people_clerkSync;
  "people/invites": typeof people_invites;
  "people/lib/provisioning": typeof people_lib_provisioning;
  "people/members": typeof people_members;
  "people/preferences": typeof people_preferences;
  "people/presence": typeof people_presence;
  "people/requests": typeof people_requests;
  "people/sandbox": typeof people_sandbox;
  "people/tourProgress": typeof people_tourProgress;
  "people/users": typeof people_users;
  "performance/auth": typeof performance_auth;
  "performance/companies": typeof performance_companies;
  "performance/export": typeof performance_export;
  "performance/import": typeof performance_import;
  "performance/lib/aggregatedTemplate": typeof performance_lib_aggregatedTemplate;
  "performance/lib/auth": typeof performance_lib_auth;
  "performance/lib/callImport": typeof performance_lib_callImport;
  "performance/lib/interactionImport": typeof performance_lib_interactionImport;
  "performance/lib/kpi": typeof performance_lib_kpi;
  "performance/lib/permissions": typeof performance_lib_permissions;
  "performance/lib/reports": typeof performance_lib_reports;
  "performance/lib/salesforceImport": typeof performance_lib_salesforceImport;
  "performance/lib/types": typeof performance_lib_types;
  "performance/lib/workdays": typeof performance_lib_workdays;
  "performance/lib/xlsxZip": typeof performance_lib_xlsxZip;
  "performance/queries": typeof performance_queries;
  "performance/roles": typeof performance_roles;
  "performance/topics": typeof performance_topics;
  "performance/uploadParse": typeof performance_uploadParse;
  performanceAuth: typeof performanceAuth;
  performanceExport: typeof performanceExport;
  performanceImport: typeof performanceImport;
  performanceQueries: typeof performanceQueries;
  performanceTopics: typeof performanceTopics;
  performanceUploadParse: typeof performanceUploadParse;
  presence: typeof presence;
  "salesCoachEv/calls": typeof salesCoachEv_calls;
  "salesCoachEv/settings": typeof salesCoachEv_settings;
  "salesCoachEv/wiki": typeof salesCoachEv_wiki;
  salesCockpit: typeof salesCockpit;
  "salesCockpit/flows": typeof salesCockpit_flows;
  "salesCockpit/lexikon": typeof salesCockpit_lexikon;
  "salesCockpit/projects": typeof salesCockpit_projects;
  salesCockpitFlows: typeof salesCockpitFlows;
  sandbox: typeof sandbox;
  secondaryEmails: typeof secondaryEmails;
  "security/accountLinks": typeof security_accountLinks;
  "security/lib/passwordResets": typeof security_lib_passwordResets;
  "security/passkeys": typeof security_passkeys;
  "security/passwordResets": typeof security_passwordResets;
  "security/secondaryEmails": typeof security_secondaryEmails;
  "security/stepUp": typeof security_stepUp;
  "security/totp": typeof security_totp;
  sharing: typeof sharing;
  stepUp: typeof stepUp;
  suggestionCategories: typeof suggestionCategories;
  suggestions: typeof suggestions;
  "suggestions/categories": typeof suggestions_categories;
  "suggestions/suggestions": typeof suggestions_suggestions;
  "tables/activity": typeof tables_activity;
  "tables/ai": typeof tables_ai;
  "tables/chat": typeof tables_chat;
  "tables/comms": typeof tables_comms;
  "tables/content": typeof tables_content;
  "tables/hr": typeof tables_hr;
  "tables/identity": typeof tables_identity;
  "tables/integrations": typeof tables_integrations;
  "tables/itTickets": typeof tables_itTickets;
  "tables/marketing": typeof tables_marketing;
  "tables/performance": typeof tables_performance;
  "tables/sales": typeof tables_sales;
  "tables/security": typeof tables_security;
  totp: typeof totp;
  tourProgress: typeof tourProgress;
  updates: typeof updates;
  "updates/email": typeof updates_email;
  "updates/internal": typeof updates_internal;
  "updates/lib/updates": typeof updates_lib_updates;
  "updates/updates": typeof updates_updates;
  updatesEmail: typeof updatesEmail;
  updatesInternal: typeof updatesInternal;
  userPreferences: typeof userPreferences;
  users: typeof users;
  whitepaperLeads: typeof whitepaperLeads;
  "wiki/categories": typeof wiki_categories;
  "wiki/chats": typeof wiki_chats;
  "wiki/entries": typeof wiki_entries;
  "wiki/formatSettings": typeof wiki_formatSettings;
  "wiki/migration": typeof wiki_migration;
  wikiCategories: typeof wikiCategories;
  wikiChats: typeof wikiChats;
  wikiEntries: typeof wikiEntries;
  wikiFormatSettings: typeof wikiFormatSettings;
  wikiMigration: typeof wikiMigration;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
