/**
 * Wallbox campaign dashboard: the two campaign reports go in through the
 * normal upload, only into a Wallbox dashboard; the shared call report
 * reaches every dashboard whose team has the agent; leads see the team view,
 * employees only their own row.
 */
import { convexTest } from "convex-test";
import { describe, expect, test } from "vitest";

import { api } from "../_generated/api";
import { type Id } from "../_generated/dataModel";
import schema from "../schema";
import { modules } from "../test.setup";
import { parseMemberStatus, readWallboxExport, summarizeMembers } from "./lib/wallboxImport";

const serverKey = "test-server-key";

function membersCsv(asOf: string, statuses: string[]): string {
  return [
    "KI_DashboardData_Wallbox_Leads",
    `As of ${asOf} Mitteleuropäische Normalzeit/MEZ • Generated by Test`,
    "Campaign Name equals DEU_2026_EV Test",
    "Customer Number;Account Name;First Name;Last Name;Member Status",
    ...statuses.map((s, i) => `${1000 + i};Firma ${i};Vor;Nach;${s}`),
    `Total;Count;${statuses.length}`,
  ].join("\n");
}

function oppsCsv(asOf: string, rows: [string, string, string, boolean, boolean][]): string {
  return [
    "KI_DashboardData_Wallbox_Opps",
    `As of ${asOf} MEZ`,
    "Primary Campaign Source equals DEU_2026_EV Test",
    "Opportunity Owner;Account Name;Acquired By;Closed;Won",
    ...rows.map(([o, a, by, c, w]) => `${o};${a};${by};${c};${w}`),
    `Total;Sum;;1;0`,
  ].join("\n");
}

function callCsv(rows: [string, number][]): string {
  return [
    "Datum;Mitarbeiter;Bearbeitet;Angenommen;Gesprächszeit gesamt;Angemeldet",
    ...rows.map(([name, n]) => `01.10.2026;${name};${n};${n};00:30:00;07:00:00`),
  ].join("\n");
}

async function setup() {
  const t = convexTest(schema, modules);
  const ids = await t.run(async (ctx) => {
    const now = Date.now();
    const user = (clerkUserId: string, role: "admin" | "employee", first: string, last: string) =>
      ctx.db.insert("users", {
        clerkUserId,
        email: `${clerkUserId}@advantisgroup.de`,
        firstName: first,
        lastName: last,
        role,
        status: "active",
        external: false,
        createdAt: now,
      });
    const admin = await user("admin", "admin", "Ada", "Admin");
    const lead = await user("lead", "employee", "Jörg", "Endres");
    const nadine = await user("nadine", "employee", "Nadine", "Weidenhammer");
    const vahan = await user("vahan", "employee", "Vahan", "Hovhannisyan");
    const olga = await user("olga", "employee", "Olga", "Onboarding");

    const team = (name: string, slug: string, reportsToUserId?: Id<"users">) =>
      ctx.db.insert("teams", { name, slug, reportsToUserId, createdAt: now, createdBy: admin });
    const evTeam = await team("EV-Pilot", "ev", lead);
    const onboardingTeam = await team("Onboarding", "onboarding");
    for (const u of [nadine, vahan])
      await ctx.db.insert("userTeams", { userId: u, teamId: evTeam });
    await ctx.db.insert("userTeams", { userId: olga, teamId: onboardingTeam });

    const dashboard = (
      name: string,
      slug: string,
      kind: "sales" | "wallbox" | "calls",
      teamIds: Id<"teams">[],
    ) => ctx.db.insert("companies", { name, slug, kind, teamIds, createdAt: now, updatedAt: now });
    const sales = await dashboard("Sales", "sales", "sales", []);
    const wallbox = await dashboard("Wallbox", "wallbox", "wallbox", [evTeam]);
    const onboarding = await dashboard("Onboarding", "onboarding", "calls", [onboardingTeam]);
    await ctx.db.insert("performanceEmployees", {
      name: "Sam Sales",
      active: true,
      companyId: sales,
    });
    return { admin, lead, nadine, vahan, olga, sales, wallbox, onboarding };
  });

  let n = 0;
  async function upload(companyId: Id<"companies">, filename: string, content: string) {
    const storageId = await t.run((ctx) =>
      ctx.storage.store(new Blob([new TextEncoder().encode(content)])),
    );
    n++;
    return t.action(api.performance.uploadParse.apiImportReport, {
      serverKey,
      companyId,
      filename,
      storageId,
      contentHash: `hash-${n}`,
    });
  }
  return { t, ids, upload, as: (s: string) => t.withIdentity({ subject: s }) };
}

describe("member status parsing", () => {
  test("splits employee, typo and EV suffix", () => {
    expect(parseMemberStatus("In Progess - Michael")).toEqual({
      status: "In Progress",
      employee: "Michael",
      ev: false,
    });
    expect(parseMemberStatus("In Progress- Nadine - min. 1 EV")).toEqual({
      status: "In Progress",
      employee: "Nadine",
      ev: true,
    });
    expect(parseMemberStatus("Interested - Opp created - min. 1 EV")).toEqual({
      status: "Interested - Opportunity created",
      ev: true,
    });
    expect(parseMemberStatus("not interested")).toEqual({ status: "Not interested", ev: false });
  });

  test("summary counts per status and per employee", () => {
    const parsed = readWallboxExport(
      membersCsv("2026-10-06 16:51:40", [
        "In Progress- Nadine",
        "In Progress- Nadine - min. 1 EV",
        "In Progess - Vahan",
        "not interested",
        "To be contacted - min. 1 EV",
      ])
        .split("\n")
        .map((l) => l.split(";")),
    );
    expect(parsed?.kind).toBe("members");
    expect(parsed?.campaign).toBe("DEU_2026_EV Test");
    const s = summarizeMembers(parsed!.kind === "members" ? parsed!.rows : []);
    expect(s.total).toBe(5);
    expect(s.people).toEqual([
      { name: "Nadine", inProgress: 2, inProgressEv: 1 },
      { name: "Vahan", inProgress: 1, inProgressEv: 0 },
    ]);
    expect(s.statuses[0]).toEqual({ status: "In Progress", count: 3, ev: 1 });
  });
});

describe("wallbox dashboard", () => {
  test("imports both reports and builds the team view", async () => {
    const { ids, upload, as } = await setup();
    const opps = await upload(
      ids.wallbox,
      "opps.csv",
      oppsCsv("2026-10-06", [
        ["Andreas Horn", "A GmbH", "Nadine WEIDENHAMMER", false, false],
        ["Andreas Horn", "B GmbH", "Nadine WEIDENHAMMER", true, false],
        ["Sascha Quadt", "C GmbH", "Vahan HOVHANNISYAN", true, true],
        ["Sascha Quadt", "D GmbH", "Michael Eysselein", false, false],
      ]),
    );
    expect(opps).toMatchObject({
      status: "ok",
      reportKind: "wallbox_opps",
      reportDate: "2026-10-06",
    });
    const members = await upload(
      ids.wallbox,
      "members.csv",
      membersCsv("2026-10-06 16:51:40", [
        "In Progress- Nadine",
        "In Progess - Michael",
        "not interested",
      ]),
    );
    expect(members).toMatchObject({ status: "ok", reportKind: "wallbox_members", skipped: [] });

    const view = await as("lead").query(api.performance.wallbox.overview, {
      companyId: ids.wallbox,
    });
    expect(view.totals).toEqual({ members: 3, inProgress: 2, opps: 4, open: 2, won: 1, lost: 1 });
    // Rows join across both reports and show the intranet spelling.
    const byName = Object.fromEntries(view.people.map((p) => [p.name.toLowerCase(), p]));
    expect(view.people.map((p) => p.name)).toContain("Nadine Weidenhammer");
    expect(byName["nadine weidenhammer"]).toMatchObject({
      inProgress: 1,
      opps: 2,
      open: 1,
      lost: 1,
    });
    expect(byName["vahan hovhannisyan"]).toMatchObject({ opps: 1, won: 1 });
    expect(byName["michael eysselein"]).toMatchObject({ inProgress: 1, opps: 1 });
    expect(view.owners.map((o) => [o.name, o.opps, o.lost, o.won])).toEqual([
      ["Andreas Horn", 2, 1, 0],
      ["Sascha Quadt", 2, 0, 1],
    ]);
    expect(view.history).toHaveLength(1);

    // Vahan (EV team member, intranet-linked) sees only his own row and list.
    const me = await as("vahan").query(api.performance.access.me, {});
    const mine = me.dashboards.find((d) => d.kind === "wallbox")!;
    expect(mine.canViewTeam).toBe(false);
    const own = await as("vahan").query(api.performance.wallbox.employee, {
      employeeId: mine.employeeId!,
    });
    expect(own?.row).toMatchObject({ opps: 1, won: 1 });
    await expect(
      as("vahan").query(api.performance.wallbox.overview, { companyId: ids.wallbox }),
    ).rejects.toThrow("Team-Ansicht");
    const list = await as("vahan").query(api.performance.wallbox.oppList, {
      companyId: ids.wallbox,
      by: "acquirer",
      employeeId: mine.employeeId!,
    });
    expect(list.rows.map((r) => r.account)).toEqual(["C GmbH"]);
    await expect(
      as("vahan").query(api.performance.wallbox.oppList, {
        companyId: ids.wallbox,
        by: "owner",
        name: "Andreas Horn",
      }),
    ).rejects.toThrow("Kein Zugriff");
  });

  test("Wallbox reports are refused on other dashboards and Salesforce reports on Wallbox", async () => {
    const { ids, upload } = await setup();
    await expect(
      upload(ids.sales, "opps.csv", oppsCsv("2026-10-06", [["A", "B", "C", false, false]])),
    ).rejects.toThrow("Wallbox-Dashboard");
    await expect(
      upload(
        ids.wallbox,
        "lead.csv",
        "As of 2026-10-05\nLead Owner;Lead Status;Create Date;Last Activity\nNadine Weidenhammer;Open;01.10.2026;",
      ),
    ).rejects.toThrow("Sales-Dashboard");
  });

  test("one call report reaches every dashboard whose team has the agent", async () => {
    const { t, ids, upload } = await setup();
    const result = await upload(
      ids.sales,
      "calls.csv",
      callCsv([
        ["Sam Sales", 10],
        ["WEIDENHAMMER Nadine", 20],
        ["Onboarding Olga", 5],
        ["Unbekannt Udo", 1],
      ]),
    );
    expect(result).toMatchObject({ status: "ok", reportKind: "call", skipped: ["Unbekannt Udo"] });
    expect((result as { alsoImportedInto?: string[] }).alsoImportedInto?.sort()).toEqual([
      "Onboarding",
      "Wallbox",
    ]);
    const calls = await t.run(async (ctx) => {
      const out: Record<string, number | undefined> = {};
      for (const companyId of [ids.sales, ids.wallbox, ids.onboarding]) {
        const reports = await ctx.db
          .query("performanceReports")
          .withIndex("by_company_reportDate", (q) => q.eq("companyId", companyId))
          .collect();
        const company = await ctx.db.get(companyId);
        out[company!.name] = reports.reduce((a, r) => a + (r.callsToday ?? 0), 0);
      }
      const logs = await ctx.db.query("performanceUploadLog").collect();
      return { out, logs: logs.length };
    });
    expect(calls.out).toEqual({ Sales: 10, Wallbox: 20, Onboarding: 5 });
    expect(calls.logs).toBe(3);

    // Uploading the same file again on another dashboard is a duplicate there.
    const again = await t.run((ctx) =>
      ctx.db
        .query("performanceUploadLog")
        .withIndex("by_company_contentHash", (q) => q.eq("companyId", ids.onboarding))
        .first(),
    );
    expect(again?.reportKind).toBe("call");
  });
});
