// Generated by scripts/vercel-preview-convex-api-build.sh during a Vercel
// Preview/Development build — see that script and convex.ts's getConvex()
// for how this is used. Committed with an empty default so local dev and
// `tsc --noEmit` never fail on a missing module; a Preview build overwrites
// this file on disk before bundling, but that change only ever lives inside
// that one CI build's filesystem and is never committed back.
export const CONVEX_PREVIEW_URL = "";
