#!/usr/bin/env bash
# Wraps apps/api's Vercel build so Preview/Development deployments talk to
# the SAME branch-scoped Convex backend apps/intranet's build claims via
# vercel-preview-convex-build.sh (Convex's preview-deployments feature keys
# a backend by project + branch name, so resolving it again here for the
# same branch reuses that exact deployment rather than creating another
# one). Production keeps building exactly as before — this only ever
# touches the generated file on a Preview/Development build.
#
# apps/api is a plain server, not a Next.js app: there's no client bundle
# to inline a NEXT_PUBLIC_* value into the way vercel-preview-convex-build.sh
# does, and a Vercel serverless function's runtime env vars come from the
# project's stored Environment Variables, not from whatever a build
# subprocess happened to export — so a build-time-resolved URL can't reach
# the deployed function as an env var at all. Instead, this writes the
# resolved URL into a source file (apps/api/src/lib/convexPreviewUrl.
# generated.ts) that convex.ts imports; since that file is a real dependency
# on disk when Vercel's builder traces/bundles the function, whatever value
# is in it at that moment ships with the deployment.
set -euo pipefail

BUILD_CMD="$1" # e.g. "tsc --noEmit"

ROOT="$(git rev-parse --show-toplevel)"
GENERATED_FILE="$ROOT/apps/api/src/lib/convexPreviewUrl.generated.ts"

log() {
  echo "[convex-preview-api] $(date -u +%FT%TZ) $*"
}

write_url() {
  cat > "$GENERATED_FILE" <<EOF
// Generated by scripts/vercel-preview-convex-api-build.sh during this
// Vercel build — do not edit by hand, this is overwritten every build.
export const CONVEX_PREVIEW_URL = "$1";
EOF
}

if [ -z "${VERCEL_ENV:-}" ]; then
  # See vercel-preview-convex-build.sh's matching comment: don't guess this
  # is a preview build when Vercel hasn't told us so.
  log "VERCEL_ENV is unset - building as-is, leaving convexPreviewUrl.generated.ts untouched"
  eval "$BUILD_CMD"
elif [ "$VERCEL_ENV" = "production" ]; then
  log "VERCEL_ENV=production - skipping Convex preview resolution, building as-is"
  eval "$BUILD_CMD"
else
  log "VERCEL_ENV=${VERCEL_ENV:-unset} branch=${VERCEL_GIT_COMMIT_REF:-unknown} - resolving this branch's Convex preview backend"

  DEPLOY_LOG="$(mktemp)"
  trap 'rm -f "$DEPLOY_LOG"' EXIT

  # 2>&1 matters: without --cmd, convex CLI appears to print its "✔
  # Deployed Convex functions to https://…" confirmation to stderr rather
  # than stdout (vercel-preview-convex-build.sh never needs this fallback
  # parse at all — it gets the URL handed to it directly via
  # --cmd-url-env-var-name — so this divergence never showed up there).
  # Confirmed against a real Preview build log: the line was visible in
  # Vercel's build output, which merges both streams, but absent from a
  # stdout-only tee.
  (cd "$ROOT/packages/convex" && npx convex deploy) 2>&1 | tee "$DEPLOY_LOG"

  # convex CLI's own deploy summary line is what's parsed here. Its
  # spinner/progress output uses \r redraws and ANSI codes that can leave a
  # stray control byte inside the domain string, breaking a plain grep even
  # though the line looks clean once a terminal renders it. Normalize \r to
  # \n and strip ANSI (CSI + OSC) sequences before matching.
  CONVEX_URL="$(
    tr '\r' '\n' < "$DEPLOY_LOG" \
      | sed -E 's/\x1b\[[0-9;]*[a-zA-Z]//g; s/\x1b\][0-9]+;[^\x07]*\x07//g' \
      | grep -oE 'https://[a-zA-Z0-9.-]+\.convex\.cloud' \
      | tail -1 || true
  )"
  if [ -n "$CONVEX_URL" ]; then
    log "resolved backend: $CONVEX_URL - writing to convexPreviewUrl.generated.ts"
    write_url "$CONVEX_URL"
  else
    log "could not resolve a backend URL from convex deploy output - leaving convexPreviewUrl.generated.ts untouched"
  fi

  eval "$BUILD_CMD"
fi
