// Moved to `hr/applicants.ts`. Re-exported so the old `api.applicants.*`
// path keeps working for open tabs and queued jobs until the shim cleanup
// in docs/future-features/22_convex-restructure.md.
export {
  listProfiles,
  createProfile,
  updateProfile,
  removeProfile,
  pipelineCount,
  list,
  get,
  create,
  update,
  remove,
  addKontakt,
  removeKontakt,
  addEmail,
  removeEmail,
  addInterview,
  removeInterview,
  generateUploadUrl,
  stagedFileUrl,
  addDocument,
  removeDocument,
  createTermin,
  listTermine,
  removeTermin,
  convertTermin,
  apiCheckAccess,
  apiFindDuplicateByContact,
  apiListProfiles,
  apiGenerateStagingUrl,
  apiCreateFromExtraction,
} from "./hr/applicants";
