// Moved to `performance/auth.ts`. Re-exported so the old `api.performanceAuth.*`
// path keeps working for open tabs and queued jobs until the shim cleanup
// in docs/future-features/22_convex-restructure.md.
export {
  getLoginByCompanyEmail,
  getSuperAdminLoginByEmail,
  createLoginIfMissing,
  createSuperAdminLoginIfMissing,
  canSetUpAccount,
  setupAccount,
  canSetUpSuperAdmin,
  setupSuperAdminAccount,
  createSession,
  login,
  checkLegacyPasswordSunset,
  legacyPasswordSunsetNotice,
  createSessionForLinkedAccount,
  validateSession,
  touchSession,
  logout,
  assertAdminSession,
  assertSuperAdminSession,
  sessionLoginDoc,
  getLoginById,
  insertLogin,
  getLoginLinkedTo,
  findAutoLinkCandidateForCompany,
  reconcileAutoLinks,
  setPasswordHash,
  listLogins,
  listEmployeesForLink,
  listIntranetUsersForLink,
  myLinkableClerkIdentity,
  linkMyAccount,
  createLogin,
  updateLogin,
  setSuperAdmin,
  resetLoginPassword,
  changeOwnPassword,
} from "./performance/auth";
