// Moved to `security/stepUp.ts`. Re-exported so the old `api.stepUp.*`
// path keeps working for open tabs and queued jobs until the shim cleanup
// in docs/future-features/22_convex-restructure.md.
export {
  orgPolicy,
  setOrgPolicy,
  apiRequestEmailCode,
  apiSubmitEmailCode,
  apiRecordVerification,
  apiRecordPasskeyStepUp,
  apiIssuePasskeyTicket,
  apiClaimPasskeyTicket,
  apiDestructiveGate,
  apiEvaluateDevice,
  status,
  areaAccessStatus,
  areaPreference,
  setAreaPreference,
  trustedDevices,
  sessionDevices,
  forgetUntrustedDevices,
  renameDevice,
  revokeDeviceTrust,
  securityPreference,
  setSecurityPreference,
  securityActivity,
  orgStandard,
  areaStandard,
  legacyPasswordStandard,
  purgeStaleDevices,
} from "./security/stepUp";
