// Moved to `people/users.ts`. Re-exported so the old `api.users.*`
// path keeps working for open tabs and queued jobs until the shim cleanup
// in docs/future-features/22_convex-restructure.md.
export {
  me,
  callerForAction,
  ensureCurrentUser,
  setSandboxRole,
  list,
  directoryList,
  get,
  myConnections,
  orgContext,
  applyProfileUpdate,
  updateProfile,
  setExpertise,
  setUpdatesEmailConsent,
  setRole,
  setCustomRoles,
  setTeams,
  setManager,
  setManagingDirector,
  setHireDate,
  applyStatus,
  setStatus,
  applyGfAccess,
  setGfAccess,
  applyUploadPermission,
  setUploadPermission,
  todaysCelebrations,
  departments,
  setApplicantDelegate,
  setApplicantAccess,
  eligibleForApplicantAccess,
  setRoleLabel,
  accessReviewList,
  markAccessReviewed,
  exportMine,
} from "./people/users";
